// <auto-generated />
using System;
using AsuTask.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AsuTask.Migrations
{
    [DbContext(typeof(AsuTestContext))]
    [Migration("20221007143532_InsertBookData")]
    partial class InsertBookData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("AsuTask.Repository.Enitites.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AuthorName");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Genre");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("72fa84cf-6a30-4e1b-b15f-deb91b52e068"),
                            AuthorName = "A",
                            Genre = "B",
                            Name = "Gg"
                        },
                        new
                        {
                            Id = new Guid("a85fee86-498e-4b4a-97f8-bab9ca414f4b"),
                            AuthorName = "Ab",
                            Genre = "Bd",
                            Name = "Gg1"
                        },
                        new
                        {
                            Id = new Guid("3c50870c-5e4c-4826-a1be-3b8c53c70066"),
                            AuthorName = "Ag",
                            Genre = "Bdd",
                            Name = "Gg4"
                        },
                        new
                        {
                            Id = new Guid("965c12e4-496e-49e2-95d3-009d03be064e"),
                            AuthorName = "Ads",
                            Genre = "Bxx",
                            Name = "Gg77"
                        },
                        new
                        {
                            Id = new Guid("18be4a4e-01d4-4edb-8038-b74d2a63f87d"),
                            AuthorName = "A1",
                            Genre = "Bd2",
                            Name = "hhh2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
