// <auto-generated />
using System;
using AsuTask.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AsuTask.Migrations
{
    [DbContext(typeof(AsuTestContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("AsuTask.DAL.Enitites.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4d4058e-f67a-4901-9c17-19453c61a41e"),
                            Login = "test@gmail.com",
                            Password = "111111"
                        });
                });

            modelBuilder.Entity("AsuTask.Repository.Enitites.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AuthorName");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Genre");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("34be676d-256c-4471-ae01-5683c280678b"),
                            AuthorName = "A",
                            Genre = "B",
                            Name = "Gg"
                        },
                        new
                        {
                            Id = new Guid("ebf4194e-89f8-4cb4-a6ae-c0f7aa7a4150"),
                            AuthorName = "Ab",
                            Genre = "Bd",
                            Name = "Gg1"
                        },
                        new
                        {
                            Id = new Guid("1732ab9c-ac13-49d6-86a0-f702095c3631"),
                            AuthorName = "Ag",
                            Genre = "Bdd",
                            Name = "Gg4"
                        },
                        new
                        {
                            Id = new Guid("af5cf798-7855-448e-add3-d4b9857319f5"),
                            AuthorName = "Ads",
                            Genre = "Bxx",
                            Name = "Gg77"
                        },
                        new
                        {
                            Id = new Guid("89021ba1-210a-48ea-9019-99f9d7866513"),
                            AuthorName = "A1",
                            Genre = "Bd2",
                            Name = "hhh2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
